# Generated by Django 2.1.5 on 2019-02-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DnsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, verbose_name='域名')),
                ('ipaddress', models.CharField(max_length=100, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Assets',
                'verbose_name_plural': 'Assets',
            },
        ),
    ]
