# Generated by Django 2.1.5 on 2019-02-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20190209_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainlist',
            name='domain',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='domainlist',
            name='ipaddress',
            field=models.GenericIPAddressField(null=True, verbose_name='IP'),
        ),
    ]
